spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true  #to make capital case to lower case in URL

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "gateway server"
    description: "crypto coin gateway server"
    version: "1.0.0"