spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true  #to make capital case to lower case in URL
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "gateway server"
    description: "crypto coin gateway server"
    version: "1.0.0"

logging:
  level:
    com:
      coins:
        gateway: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50 #50% is failed then move to standby
      waitDurationInOpenState: 10000 #wait for 10sec